sources:
  - name: CSM
    handler:
      openapi:
        source: ./openapi.json
        endpoint: https://zlczywhctfaosxqtjwee.supabase.co/rest/v1/
        operationHeaders:
          apikey: ${SUPABASE_CSM_API_KEY}
additionalResolvers:
  - "./resolvers"
