export const databaseTypes: Record<string, string> = {
  api: "apis",
  asic: "asics",
  container: "containers",
  contract: "contracts",
  energy: "energies",
  farm: "farms",
  financialStatement: "financialStatements",
  flow: "flows",
  location: "locations",
  mining: "mining",
  operator: "operators",
  pool: "pools",
  powerPlant: "powerPlants",
  provider: "providers",
  site: "sites",
  society: "societies",
  token: "tokens",
  vault: "vaults",
};
